services:
  server:
    depends_on:
      - db

  db:
    image: mariadb
    user: ${UID}:${GID}
    environment:
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
    restart: unless-stopped