services:
  server:
    depends_on:
      - db

  db:
    image: mariadb
    user: ${UID}:${GID}
    environment:
      - MARIADB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ${DB_VOLUME}:/var/lib/mysql
      - ${DB_SQL_PATH}:/docker-entrypoint-initdb.d:ro
    restart: unless-stopped
